### ISSUE TITLE
#1417 -  Office UI: Locking Lodgings: Warnings have gotten messed up 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#374] opened 2016-08-05 05:08 UTC
This is a new bug since 6/22.

Go reservations screen and select 8/21 date. Note that F6 and C6 are locked. Select inside F6 and select "Jamie Barton" (this will open his res). Ufreeze the window. Try to remove him from F6 by selecting the red X. You get no warning, even though the cabin is locked. Try to add him to C6 - again, no warning. Any user other than the user who placed the lock should get a warning here.

NOTE: When Gavin went back to remove Jamie from C6 to "re-set" the scenario, HE got a warning, even though he was the user who put the lock on (he should not get warnings).

**Comment by neerajkhatri-btc** [comment] 2016-08-11 06:21
@NishantUpadhyay-BTC : the client was unable to reproduce that issue so close it for now.

**Closed as completed by neerajkhatri-btc** 2016-08-11 06:21 UTC
Labels: bug
