### ISSUE TITLE
Restricted Periods not set in Office UI > Guest UI : So why Restricted Periods show in Availability Table Page

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#358] opened 2016-07-20 11:03 UTC
![welcome to breitenbush7](https://cloud.githubusercontent.com/assets/16792762/16984398/4f2f5ce8-4e97-11e6-9409-a39a1b7e81a8.png)

Expected - There r no Restricted Periods not set in Office UI so in Guest UI > Availability Table Page > should not show Restricted Periods

**Comment by NishantUpadhyay-BTC** [comment] 2016-07-26 08:52
This is not a bug. This is because of dump data. so I am closing this.

**Closed as completed by NishantUpadhyay-BTC** 2016-07-26 08:52 UTC
Labels: bug
